spring.datasource.url=jdbc:postgresql://localhost:5454/zenzmoney
spring.datasource.username=zenzmoney
spring.datasource.password=zenzmoney
spring.datasource.hikari.maximum-pool-size=10

spring.data.redis.host=localhost
spring.data.redis.port=6363

spring.thymeleaf.cache=false

logging.level.com.zenzmoney=DEBUG
logging.level.org.springframework.security=DEBUG
