habit.google.app-id=YOUR_CLIENT_ID
habit.google.app-secret=YOUR_CLIENT_SECRET
habit.google.app-redirect-url=http://localhost:8080/login/oauth/google
habit.google.ios-app-id=
habit.google.android-app-id=
