zenzmoney.google.app-id=YOUR_CLIENT_ID
zenzmoney.google.app-secret=YOUR_CLIENT_SECRET
zenzmoney.google.app-redirect-url=http://localhost:8080/login/oauth/google
zenzmoney.google.ios-app-id=
zenzmoney.google.android-app-id=
